name: maestral
title: Maestral
version: git
license: MIT
icon: maestral_qt/resources/maestral.png
summary: An open-source Dropbox client for macOS and Linux.
description: |
  Maestral is light-weight and simple Dropbox client for Linux and macOS.
  It allows two-way syncing with your Dropbox, setting up a 'mignore' file
  similar to 'gitignore' and syncing multiple Dropbox accounts.
confinement: classic
base: core18
architectures:
  - build-on: [i386, arm64]

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  maestral:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: git://github.com/samschott/maestral-dropbox
    source-type: git
    build-packages:
      - libssl-dev
      - python3
      - python3-dev
      - python3-pip
      - execstack
    stage-packages:
      - python3
      - libc-bin
      - locales
    override-build: |
      snapcraftctl build
        chmod +x /build/maestral/parts/maestral/install/bin

  maestral-qt:
    after: [maestral]
    plugin: python
    python-version: python3
    source: git://github.com/samschott/maestral-qt
    source-type: git
    build-packages:
      - libssl-dev
      - python3
      - python3-dev
      - python3-pip
      - execstack
    stage-packages:
      - python3
      - python3-pyqt5
      - libc-bin
      - locales
    override-build: |
      snapcraftctl build
      chmod +x /build/maestral/parts/maestral/install/bin

apps:
  maestral:
    command: bin/maestral
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
